// <auto-generated />
using Async_Inn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Async_Inn.Migrations
{
    [DbContext(typeof(AsyncInnDbContext))]
    partial class AsyncInnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Async_Inn.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mini Bar"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kitchenette"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Desk Work Space"
                        });
                });

            modelBuilder.Entity("Async_Inn.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Ruston",
                            Country = "United States",
                            Name = "Neutral Milk Hotel",
                            State = "Louisianna",
                            StreetAddress = "123 Avery Island St., Ruston, LA 12345"
                        },
                        new
                        {
                            Id = 2,
                            City = "Somewhere",
                            Country = "United States",
                            Name = "Grand Budapest Hotel",
                            State = "Ohklahoma",
                            StreetAddress = "123 West Anderson Dr, Somewhere, OK 23456"
                        },
                        new
                        {
                            Id = 3,
                            City = "Los Angeles",
                            Country = "United States",
                            Name = "Hotel California",
                            State = "California",
                            StreetAddress = "123 Such A Lovely Pl., Los Angeles, CA 90212"
                        });
                });

            modelBuilder.Entity("Async_Inn.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Layout = 2,
                            Name = "Executive Suite"
                        },
                        new
                        {
                            Id = 2,
                            Layout = 1,
                            Name = "Honeymoon Suite"
                        },
                        new
                        {
                            Id = 3,
                            Layout = 0,
                            Name = "Economy Plus"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
